### ISSUE TITLE
프로젝트 구성 질문

### ISSUE THREAD

**Issue by hihiboss** [Nexters/mozipmozip#29]
안녕하세요! NEXTERS 14기 김준희라고 합니다 :)

다른 팀들 레포지터리 훔쳐보다가 열심히 작업하셨길래 염탐했습니다...
열심히 구경하다가 프로젝트 구성에 대해 궁금한 점이 생겨서 이슈로 남깁니다!

1. 한 레포지터리 안에 클라이언트/서버 모듈을 모두 포함하여 구성하셨는데 혹시 그 이유가 있을까요??
제가 나름 생각해본 이유는 AWS에 올렸을 때 쉽게 관리하기 위해서...?? 인데.. 답해주시면 감사하겠습니다!!
(클라이언트 레포지터리 따로, 서버 레포지터리 따로 구성하는 경우를 많이 봐서요!)

2. 서버 디렉토리 안에서 Domain과 API를 프로젝트로 분리하셨는데 그 이유가 있을까요??
 저는 패키지로만 구분해와서.. 프로젝트로 따로 분리한 이유가 궁금합니다!!

--

제가 실력은 없는 물음표 살인마라... 궁금증을 못참고 글 남깁니다ㅠㅠ
답변주시면 정말 감사하겠습니다!!

모집모집팀 화이팅!!

**Comment by tramyu** [comment]
첫번째 질문에 대해서는.. 여러 이유가 있는데요

- 같이 묶어서 배포를 하는 경우 여러 레파지토리를 운영하면 귀찮아져서
AWS로 배포 시 프론트와 서버를 별도로 배포하게 되면 최소 2개의 인스턴스를 사용하거나
내부에서 포트를 통해 분리시켜주어야 하는데, 그게 번거로워서 같이 묶어서 배포를 하기로 했어요(벡엔드 서버에서 api 요청 시 벡엔드 요청을 받고, 이외는 React 쪽의 응답 결과를 반환하도록 설정해두었어요, 두개 같이 묶여서 배포가 나가고 있습니다.)
배포 시 같은 레파지토리가 아니면 코드를 가져오기가 불편해서 그냥 같이 묶어서 관리하는게 어떤가 하고 제안해서, 같이 사용하게 됐습니다. 큰 이유는 없어요

- 프론트 분들도 서버의 리소스를 올려서 로컬에서 통합 테스트를 할 수 있도록
그리고 프론트 분들도 대부분 어느정도 서버에 대한 지식이 있어서, 로컬에서 통합으로 테스트를 하고 싶은 경우가 많을 텐데 그 경우에 서버를 띄워서 활용할 수 있도록 그냥 같은 레파지토리에 위치시켰어요.

두번째 질문의 경우에는 대부분의 회사나, 규모가 있는 프로젝트에서 멀티모듈 구조를 사용하기 때문에 그냥 한번 경험해보면 좋을것 같다? 라는 생각에 멀티모듈로 구조를 쪼갰어요.
사실 지금 정도의 복잡도에서는 패키지를 나누는게 훨씬 좋겠죠...

**Comment by tramyu** [comment]
따로 응답이 없으셔서 close 하도록 하겠습니다!

**Comment by hihiboss** [comment]
앗 github 메일이 많아서 제가 놓쳤나봅니다 ㅠㅠ

자세하고 친절한 설명 감사합니다!! :)
